username = ENV['USER']
vm_server = username + "S"
vm_serverworker = username + "SW"
vm_memory = 1024

Vagrant.configure(2) do |config|
	config.vm.box = "debian/bookworm64"
	config.vm.synced_folder '.', '/vagrant', disabled: true
	config.vm.define vm_server do |control|
		control.vm.hostname = vm_server
		control.vm.network "private_network", ip: "192.168.56.110"
		control.vm.provider "virtualbox" do |vb|
			vb.memory = vm_memory
			vb.cpus = 1
			vb.gui = false
			vb.name = "Server"
			vb.linked_clone = true
			vb.customize ["modifyvm", :id, "--name", vm_server]
		end
		control.vm.provision :shell, path: "scripts/bootstrapServer.sh"
	end
	config.vm.define vm_serverworker do |control|
		control.vm.hostname = vm_serverworker
		control.vm.network "private_network", ip: "192.168.56.111"
		control.vm.provider "virtualbox" do |vb|
			vb.memory = vm_memory
			vb.cpus = 1
			vb.gui = false
			vb.name = "ServerWorker"
			vb.linked_clone = true
			vb.customize ["modifyvm", :id, "--name", vm_serverworker]
		end
		control.vm.provision :shell, path: "scripts/bootstrapServerWorker.sh"
	end
end
