Vagrant.configure(2) do |config|
	# config.vm.box = "debian/bookworm64"
	config.vm.box = "centos/7"
	config.vm.synced_folder '.', '/vagrant', disabled: true
	config.vm.define "epresa-cS" do |control|
		control.vm.hostname = "epresa-cS"
		control.vm.network "private_network", ip: "192.168.56.110"
		control.vm.provider "virtualbox" do |vb|
			vb.memory = "512"
			vb.cpus = 1
			vb.gui = false
			vb.name = "Server"
			vb.linked_clone = true
			# use of VBoxManage Customizations to make modifications to VirtualBox virtual machines
			# https://developer.hashicorp.com/vagrant/docs/providers/virtualbox/configuration#vboxmanage-customizations
			# https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm
			vb.customize ["modifyvm", :id, "--name", "epresa-cS"]
		end
		control.vm.provision :shell, path: "scripts/bootstrapServer.sh"
	end
	config.vm.define "epresa-cSW" do |control|
		control.vm.hostname = "epresa-cSW"
		control.vm.network "private_network", ip: "192.168.56.111"
		control.vm.provider "virtualbox" do |vb|
			vb.memory = "512"
			vb.cpus = 1
			vb.gui = false
			vb.name = "ServerWorker"
			vb.linked_clone = true
			# use of VBoxManage Customizations to make modifications to VirtualBox virtual machines
			# https://developer.hashicorp.com/vagrant/docs/providers/virtualbox/configuration#vboxmanage-customizations
			# https://www.virtualbox.org/manual/ch08.html#vboxmanage-modifyvm
			vb.customize ["modifyvm", :id, "--name", "epresa-cSW"]
		end
		control.vm.provision :shell, path: "scripts/bootstrapServerWorker.sh"
	end
end
