mate:
	ansible-playbook --ask-become-pass --inventory hosts playbooks/mate.yaml

ssh:
	ansible-playbook --ask-become-pass --inventory hosts playbooks/sshd.yaml

ufw:
	ansible-playbook --ask-become-pass --inventory hosts playbooks/ufw.yaml

iot:
	ansible-playbook --ask-become-pass --inventory hosts playbooks/iot.yaml
