= P3: Argo CD and k3d

== Theory

There is a server with

* k3d
* Docker
* kubectl
* argocd

k3d generate a k3d container (`ghcr.io/k3d-io/k3d-proxy:5.7.3`) and a few other k3s container (`rancher/k3s:v1.30.3-k3s1`).

== Setup

. Create the cluster
+
----
k3d cluster create cluster-${USER} --api-port 6445
----

. Create the argo CD namespace
+
----
kubectl create namespace argocd
----

. Apply the install of argocd
+
----
kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
----

. Generate tls ssl certificate
+
[source,bash]
----
#!/bin/sh

HOSTNAME=$(cat /etc/hostname)

################################################################################

SERVER_PATH="."
SERVER_KEY="${SERVER_PATH}/server.key"
SERVER_CSR="${SERVER_PATH}/server.csr"
SERVER_CRT="${SERVER_PATH}/server.crt"
EXTFILE="${SERVER_PATH}/cert_ext.cnf"

cat > ${EXTFILE} << eof
[req]
default_bit = 4096
distinguished_name = req_distinguished_name
prompt = no

[req_distinguished_name]
countryName             = CH
stateOrProvinceName     = Vaud
localityName            = Lausanne
organizationName        = 42Lausanne
commonName              = ${HOSTNAME}
eof

echo "Generating private key"
openssl genrsa -out ${SERVER_KEY} 4096

echo "Generating Certificate Signing Request"
openssl req -new -key ${SERVER_KEY} -out ${SERVER_CSR} -config ${EXTFILE}

echo "Generating self signed certificate"
openssl x509 -req -days 3650 -in ${SERVER_CSR} -signkey ${SERVER_KEY} -out ${SERVER_CRT}
----

. Set certificate and key (see: https://argo-cd.readthedocs.io/en/stable/operator-manual/tls/#inbound-tls-certificates-used-by-argocd-repo-server[command])
+
----
kubectl create -n argocd secret tls argocd-server-tls \
  --cert=/home/${USER}/server.crt \
  --key=/home/${USER}/server.key
----

. port forward port
+
----
kubectl port-forward svc/argocd-server -n argocd 10999:443
----

. bind port over ssh
+
----
ssh iot -L 10999:localhost:10999
----

. open your browser
+
----
firefox https://localhost:10999
----

. get the admin password
+
----
kubectl --namespace argocd get secret argocd-initial-admin-secret -o jsonpath="{.data.pass
word}" |
base64 -d
----

. set an admin password
+
----
argocd admin initial-password -n argocd
----

. TODO configure the auto update of application

== Replace port-forward command

With https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#create-a-service[create a service]

----
kubectl --namespace argocd expose svc/argocd-server --port=443 --target-port=8443 --name=argocd-https
----

I got

----
$ kubectl get svc
NAME         TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
kubernetes   ClusterIP   10.43.0.1    <none>        443/TCP   99m
----

== Apply simple example from the documentation

____
https://k3d.io/v5.7.3/usage/exposing_services/[exposing services]
____

with this file: `thatfile.yaml`

[source,yaml]
----
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nginx
            port:
              number: 80
----
and them commands, we have access to the nginx
----
CLUSTER_NAME="cluster-${USER}"
k3d cluster create "${CLUSTER_NAME}" --api-port 6445 --port 42443:443@loadbalancer --port 42080:80@loadbalancer
kubectl create deployment nginx --image=nginx
kubectl create service clusterip nginx --tcp=80:80
kubectl apply -f thatfile.yaml
curl localhost:42080/
----

from `kubectl create service clusterip --help`
----
--tcp=[]:
    Port pairs can be specified as '<port>:<targetPort>'.
----

TODO look this and adapt the manual to our situation with argocd

- change rules http with https ?
- user port number 443 instead of 80
- ssl redirect, switch to true instead of false
