= My notes

== Documentation

. Launch machines
+
----
vagrant up
----

== Journal

=== Try to use qemu instead of virtual box

. Replace virtualbox with qemu in `p1/Vagrantfile`
+
[source, patch]
----
    ...
-   control.vm.provider "virtualbox" do |vb|
-           vb.memory = "512"
+   control.vm.provider "qemu" do |qe|
+           qe.memory = "512"
    ...
----

. Install libvirt plugin with vagrant
+
----
vagrant plugin install vagrant-libvrt
vagrant plugin install libvrt
----
+
but I receive this error message
+
----
Vagrant failed to load a configured plugin source. This can be caused
by a variety of issues including: transient connectivity issues, proxy
filtering rejecting access to a configured plugin source, or a configured
plugin source not responding correctly. Please review the error message
below to help resolve the issue:

  Net::OpenTimeout: Failed to open TCP connection to gems.hashicorp.com:443 (execution expired) (https://gems.hashicorp.com/specs.4.8.gz)

Source: https://gems.hashicorp.com/
----

=== Install virtualbox on archlinux

Install "virtualbox-host-modules-arch" for my Arch Linux

Install virtualbox plugin
+
----
vagrant plugin install virtualbox
----
+
I receive this
+
----
The provider 'virtualbox' that was requested to back the machine
'epresa-cS' is reporting that it isn't usable on this system. The
reason is shown below:

VirtualBox is complaining that the kernel module is not loaded. Please
run `VBoxManage --version` or open the VirtualBox GUI to see the error
message which should contain instructions on how to fix this error.
----

I reboot my computer to load the `vboxdrv` kernel module

=== Launch vagrant

----
vagrant up
----
+
----
$ vagrant up
Bringing machine 'epresa-cS' up with 'virtualbox' provider...
Bringing machine 'epresa-cSW' up with 'virtualbox' provider...
==> epresa-cS: Box 'centos/7' could not be found. Attempting to find and install...
    epresa-cS: Box Provider: virtualbox
    epresa-cS: Box Version: >= 0
==> epresa-cS: Loading metadata for box 'centos/7'
    epresa-cS: URL: https://vagrantcloud.com/api/v2/vagrant/centos/7
==> epresa-cS: Adding box 'centos/7' (v2004.01) for provider: virtualbox
    epresa-cS: Downloading: https://vagrantcloud.com/centos/boxes/7/versions/2004.01/providers/virtualbox/unknown/vagrant.box
Download redirected to host: cloud.centos.org
    epresa-cS: Calculating and comparing box checksum...
==> epresa-cS: Successfully added box 'centos/7' (v2004.01) for 'virtualbox'!
==> epresa-cS: Preparing master VM for linked clones...
    epresa-cS: This is a one time operation. Once the master VM is prepared,
    epresa-cS: it will be used as a base for linked clones, making the creation
    epresa-cS: of new VMs take milliseconds on a modern system.
==> epresa-cS: Importing base box 'centos/7'...
==> epresa-cS: Cloning VM...
==> epresa-cS: Matching MAC address for NAT networking...
==> epresa-cS: Checking if box 'centos/7' version '2004.01' is up to date...
==> epresa-cS: Setting the name of the VM: Server
==> epresa-cS: Clearing any previously set network interfaces...
==> epresa-cS: Preparing network interfaces based on configuration...
    epresa-cS: Adapter 1: nat
    epresa-cS: Adapter 2: hostonly
==> epresa-cS: Forwarding ports...
    epresa-cS: 22 (guest) => 2222 (host) (adapter 1)
==> epresa-cS: Running 'pre-boot' VM customizations...
==> epresa-cS: Booting VM...
==> epresa-cS: Waiting for machine to boot. This may take a few minutes...
    epresa-cS: SSH address: 127.0.0.1:2222
    epresa-cS: SSH username: vagrant
    epresa-cS: SSH auth method: private key
    epresa-cS:
    epresa-cS: Vagrant insecure key detected. Vagrant will automatically replace
    epresa-cS: this with a newly generated keypair for better security.
    epresa-cS:
    epresa-cS: Inserting generated public key within guest...
    epresa-cS: Removing insecure key from the guest if it's present...
    epresa-cS: Key inserted! Disconnecting and reconnecting using new SSH key...
==> epresa-cS: Machine booted and ready!
==> epresa-cS: Checking for guest additions in VM...
    epresa-cS: No guest additions were detected on the base box for this VM! Guest
    epresa-cS: additions are required for forwarded ports, shared folders, host only
    epresa-cS: networking, and more. If SSH fails on this machine, please install
    epresa-cS: the guest additions and repackage the box to continue.
    epresa-cS:
    epresa-cS: This is not an error message; everything may continue to work properly,
    epresa-cS: in which case you may ignore this message.
==> epresa-cS: Setting hostname...
==> epresa-cS: Configuring and enabling network interfaces...
==> epresa-cS: Running provisioner: shell...
    epresa-cS: Running: /tmp/vagrant-shell20240817-2566-lsaow1.sh
    epresa-cS: bootstrapping server...
==> epresa-cSW: Box 'centos/7' could not be found. Attempting to find and install...
    epresa-cSW: Box Provider: virtualbox
    epresa-cSW: Box Version: >= 0
==> epresa-cSW: Loading metadata for box 'centos/7'
    epresa-cSW: URL: https://vagrantcloud.com/api/v2/vagrant/centos/7
==> epresa-cSW: Adding box 'centos/7' (v2004.01) for provider: virtualbox
==> epresa-cSW: Cloning VM...
==> epresa-cSW: Matching MAC address for NAT networking...
==> epresa-cSW: Checking if box 'centos/7' version '2004.01' is up to date...
==> epresa-cSW: Setting the name of the VM: ServerWorker
==> epresa-cSW: Fixed port collision for 22 => 2222. Now on port 2200.
==> epresa-cSW: Clearing any previously set network interfaces...
==> epresa-cSW: Preparing network interfaces based on configuration...
    epresa-cSW: Adapter 1: nat
    epresa-cSW: Adapter 2: hostonly
==> epresa-cSW: Forwarding ports...
    epresa-cSW: 22 (guest) => 2200 (host) (adapter 1)
==> epresa-cSW: Running 'pre-boot' VM customizations...
==> epresa-cSW: Booting VM...
==> epresa-cSW: Waiting for machine to boot. This may take a few minutes...
    epresa-cSW: SSH address: 127.0.0.1:2200
    epresa-cSW: SSH username: vagrant
    epresa-cSW: SSH auth method: private key
    epresa-cSW:
    epresa-cSW: Vagrant insecure key detected. Vagrant will automatically replace
    epresa-cSW: this with a newly generated keypair for better security.
    epresa-cSW:
    epresa-cSW: Inserting generated public key within guest...
    epresa-cSW: Removing insecure key from the guest if it's present...
    epresa-cSW: Key inserted! Disconnecting and reconnecting using new SSH key...
==> epresa-cSW: Machine booted and ready!
==> epresa-cSW: Checking for guest additions in VM...
    epresa-cSW: No guest additions were detected on the base box for this VM! Guest
    epresa-cSW: additions are required for forwarded ports, shared folders, host only
    epresa-cSW: networking, and more. If SSH fails on this machine, please install
    epresa-cSW: the guest additions and repackage the box to continue.
    epresa-cSW:
    epresa-cSW: This is not an error message; everything may continue to work properly,
    epresa-cSW: in which case you may ignore this message.
==> epresa-cSW: Setting hostname...
==> epresa-cSW: Configuring and enabling network interfaces...
==> epresa-cSW: Running provisioner: shell...
    epresa-cSW: Running: /tmp/vagrant-shell20240817-2566-2sojqr.sh
    epresa-cSW: bootstrapping serverWorker...
----

=== Add an environment variable to the vagrantfile

Resource: https://www.ryanchapin.com/using-environment-variables-in-a-vagrant-file/[Using Environment Variables in a Vagrant File]

[source,patch]
----
-  control.vm.hostname =  ENV['WHOAMI']
+  control.vm.hostname = "epresa-cS"
----

Add environment variable

----
$ echo $WHOAMI
epresa-cS
----

But got this after `vagrant up`

----
Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
an invalid or undefined variable.

Path: /opt/vagrant/embedded/gems/gems/vagrant-2.4.1/plugins/kernel_v2/config/vm.rb
Line number: 0
Message: undefined method `to_sym'
----

=== Connect over SSH

Launch

----
vagrant up
----

Connect with

----
vagrant ssh epresa-cS
vagrant ssh epresa-cSW
----

=== Get the sshd config

After to be connected to the machine, I print the sshd config

----
[vagrant@epresa-cS ~]$ sudo cat  /etc/ssh/sshd_config  | grep -v "^#" | grep -v "^$"
HostKey /etc/ssh/ssh_host_rsa_key
HostKey /etc/ssh/ssh_host_ecdsa_key
HostKey /etc/ssh/ssh_host_ed25519_key
SyslogFacility AUTHPRIV
AuthorizedKeysFile      .ssh/authorized_keys
PasswordAuthentication no
ChallengeResponseAuthentication no
GSSAPIAuthentication yes
GSSAPICleanupCredentials no
UsePAM yes
X11Forwarding yes
UseDNS no
AcceptEnv LANG LC_CTYPE LC_NUMERIC LC_TIME LC_COLLATE LC_MONETARY LC_MESSAGES
AcceptEnv LC_PAPER LC_NAME LC_ADDRESS LC_TELEPHONE LC_MEASUREMENT
AcceptEnv LC_IDENTIFICATION LC_ALL LANGUAGE
AcceptEnv XMODIFIERS
Subsystem       sftp    /usr/libexec/openssh/sftp-server
----

And print the public ssh key

----
[vagrant@epresa-cS ~]$ cat ~/.ssh/authorized_keys
ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOWG7FyvvixzfNOgf6pR2IgNqjtBlGO06bnVAmTIp/XD vagrant
----

It's interresting, because we can understand that vagrant create automaticly ssh keys for the connection

=== Setup a VPS

I discover a nice feature, https://en.wikipedia.org/wiki/Wake-on-LAN[Wake-on-LAN]

resouce: https://wiki.archlinux.org/title/Wake-on-LAN#On_the_same_LAN[arch wiki]

Got my mate public key with

----
curl https://github.com/${USERNAME}.keys
----

I choosed Arch linux as VPS ditribution because I am use to with this one.
And I want to know what is the best between arch and debian...

=== VPS user

----
[theo@iot ~]$ vagrant plugin install virtualbox
Installing the 'virtualbox' plugin. This can take a few minutes...
Vagrant failed to properly resolve required dependencies. These
errors can commonly be caused by misconfigured plugin installations
or transient network issues. The reported error is:

conflicting dependencies bigdecimal (= 3.1.3) and bigdecimal (= 3.1.8)
  Activated bigdecimal-3.1.8
  which does not match conflicting dependency (= 3.1.3)

  Conflicting dependency chains:
    bigdecimal (= 3.1.8), 3.1.8 activated

  versus:
    bigdecimal (= 3.1.3)

  Gems matching bigdecimal (= 3.1.3):
    bigdecimal-3.1.3
----

Configure the firewall to avoid trouble from my mates
(avoid any ping to other devices)

[source, bash]
----
ufw deny out to 192.168.1.0/24 # my LAN
ufw allow out to 192.168.1.1 # gateway
ufw default allow outgoing # get access to the web
----

=== Try to install k3s on CenOS

----
[vagrant@epresa-cS ~]$ curl -sfL https://get.k3s.io | sh -
[INFO]  Finding release for channel stable
[INFO]  Using v1.30.3+k3s1 as release
[INFO]  Downloading hash https://github.com/k3s-io/k3s/releases/download/v1.30.3+k3s1/sha256sum-amd64.txt
[INFO]  Downloading binary https://github.com/k3s-io/k3s/releases/download/v1.30.3+k3s1/k3s
[INFO]  Verifying binary download
[INFO]  Installing k3s to /usr/local/bin/k3s
[INFO]  Finding available k3s-selinux versions
Loaded plugins: fastestmirror
Determining fastest mirrors
Could not retrieve mirrorlist http://mirrorlist.centos.org/?release=7&arch=x86_64&repo=os&infra=vag error was
14: curl#6 - "Could not resolve host: mirrorlist.centos.org; Unknown error"


 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: base/7/x86_64
----

CenOS is yet deprecated (see https://rockylinux.org/about[rocky linux about]) so we changed for Debian.

=== K3S : Server and Agent

____
Resource: https://docs.k3s.io/installation/configuration#configuration-with-install-script[Configuration with install script]
____

First machine (Server)

----
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server" sh -s - --flannel-backend none --token "mypassword"
----

Second machine (ServerWorker)

----
curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="agent" K3S_TOKEN="mypassword" sh -s - --server https://192.168.56.110
----

== Meetings

=== Cyber reunion

____
2024-08-20: 12h00 on discord
____

Why CentOS ?

No particular reasons

tgrivel want to setup a VPS at home for working

== Resources

The Kubernetes Book (Nigel Poulton) : https://github.com/rohitg00/DevOps_Books/blob/main/The%20Kubernetes%20Book%20(Nigel%20Poulton)%20(z-lib.org).pdf

Kubernetes Crash Course for Absolute Beginners : https://youtu.be/s_o8dwzRlu4?si=bZlrSVcJXb9QpOOD 

Vagrant documentation : https://developer.hashicorp.com/vagrant/docs

Vagrant + K3s (vidéo en français) : https://www.youtube.com/watch?v=JLnjMCRLcCo

Vagrant cheat sheet : https://gist.github.com/wpscholar/a49594e2e2b918f4d0c4 
Pluralsight course : "Getting started with Kubernetes" 

La vidéo 04 06 présente un exemple de déploiement d'une application sur un cluster kubernetes via argo cd. La vidéo 04 02 parle également de l'interaction entre k8s et argo cd.
Kubernetes Playground : https://labs.play-with-k8s.com/ 
https://www.youtube.com/watch?v=JLnjMCRLcCo
https://portal.cloud.hashicorp.com/vagrant/discover?next=CgxXemN4TVRreU4xMD0%3D
HashiCorp Cloud Platform

=== Claude

==== what is the diference between k3s server and k3s agent ?

The main differences between a K3s server and a K3s agent are:

. Role:
** K3s server: Acts as the control plane, managing the cluster state and making global decisions.
** K3s agent: Runs workloads and communicates with the server to receive instructions.
. Components:
** K3s server: Runs etcd (or SQLite), API server, controller manager, and scheduler.
** K3s agent: Runs kubelet and kube-proxy.
. Deployment:
** K3s server: At least one is required in a cluster, can have multiple for high availability.
** K3s agent: Optional, used to add worker nodes to the cluster.
. Resource usage:
** K3s server: Generally requires more resources due to control plane components.
** K3s agent: Typically lighter on resource usage.
. Configuration:
** K3s server: Requires more configuration options for cluster management.
** K3s agent: Simpler configuration, mainly needs the server URL to join the cluster.

Would you like me to elaborate on any of these points or provide more information about K3s architecture?

==== but kubernetes has the same options?

You're right to ask about the comparison with standard Kubernetes. While K3s and standard Kubernetes share many concepts, there are some key differences:

. Simplification:
** K3s: Simplifies the server/agent distinction. A single binary can act as either server or agent.
** Kubernetes: Has a more complex architecture with separate components like kube-apiserver, kube-scheduler, etc.
. Resource footprint:
** K3s: Designed to be lightweight, with a smaller memory and CPU footprint.
** Kubernetes: Generally requires more resources, especially for the control plane.
. Installation and setup:
** K3s: Offers a simpler installation process, often with a single command.
** Kubernetes: Typically involves a more complex setup process.
. Default configurations:
** K3s: Comes with sensible defaults and built-in features like local storage provider.
** Kubernetes: Requires more manual configuration and add-ons.
. Use case focus:
** K3s: Targets edge computing, IoT, and resource-constrained environments.
** Kubernetes: Designed for a broader range of use cases, including large-scale deployments.

While K3s and Kubernetes share the server (control plane) and agent (worker) concepts, K3s simplifies this architecture to make it more accessible and lightweight. This is particularly useful for smaller deployments or resource-constrained environments.
